# Topic: Linear Algebra
#### covered: vector multiplication,
####  matrix multiplication,
#### transpose,
####  identity matrix,
####  inverse of a matrix

In [1]:
import numpy as np  

Vector operation

In [3]:
#vector multiplaction   
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v1 * v2  # element-wise multiplication

array([ 4, 10, 18])

In [5]:
#transpose of a matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
A.T

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
#vector vector multiplication
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# element-wise multiplication using a loop
if v1.shape[0] != v2.shape[0]:
    raise ValueError("Vectors must be the same length")
else:
    result=0.0
    for i in range(len(v1)):
        result=result+ v1[i] * v2[i]
    print(result)

32.0


In [8]:
v1.dot(v2)  # dot product using numpy

np.int64(32)

In [20]:
#matrix and vector multiplication

A = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([7, 8  , 9])

for i in range(A.shape[0]):
    if A.shape[1] != v.shape[0]:
        raise ValueError("Number of columns in A must be equal to number of rows in v")
    else:
        result=0.0
        for j in range(A.shape[1]):
            result=result + A[i,j] * v[j]
        print(result)


50.0
122.0


In [19]:
#matrix and vector multiplication
A = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([7, 8  , 9])
print(A)
print(v) 
print(A.shape[1])
print(v.shape[0])   
#number of columns of A should be equal to number of rows of v
if A.shape[1] != v.shape[0]:
    raise ValueError("Number of columns of A must be equal to number of rows of v")
A.dot(v)  # matrix-vector multiplication

[[1 2 3]
 [4 5 6]]
[7 8 9]
3
3


array([ 50, 122])

In [6]:
#dot product of two matrices
# A.T * B
B = np.array([[7, 8], [9, 10], [11, 12]])
A.dot(B)

array([[ 58,  64],
       [139, 154]])

In [11]:
np.random.seed(2)
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))
print(a)
print(50*"*")
print(b)
a.dot(b)
#`matrix multiplication, row of a is multiplied by column of b and summed`
# for matrix multiplication number of columns of first matrix should be equal to number of rows of second matrix
# 8*8 + 8*2 = 80
# 8*7 + 8*1 = 64
# 6*8 + 2*2 = 52
# 6*7 + 2*1 = 44
# output will be 2x2 matrix

[[8 8]
 [6 2]]
**************************************************
[[8 7]
 [2 1]]


array([[80, 64],
       [52, 44]], dtype=int32)

In [ ]:
a[0:,1] 
# second column of a

array([8, 2], dtype=int32)

In [30]:
#identity matrix
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [31]:
I.dot(a)

array([[8., 8.],
       [6., 2.]])

In [33]:
#matrix inverse
#A-1 * A = I
np.linalg.inv(a).dot(a)

#how is inverse calculated theoretically
#for 2x2 matrix
det = a[0,0]*a[1,1] - a[0,1]*a[1,0]
inv_a = (1/det) * np.array([[a[1,1], -a[0,1]], [-a[1,0], a[0,0]]])
inv_a.dot(a)

array([[1., 0.],
       [0., 1.]])