In [1]:
import pandas as pd
print(pd.__version__)

2.3.2


In [2]:
import numpy as np
print(np.__version__)

2.3.3


In [ ]:
np.zeros(10)
# array of 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.full(10,5)
# array of 10 fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [5]:
list_list=[1,2,3,4,5]
a=np.array(list_list)
a

array([1, 2, 3, 4, 5])

In [9]:
print(a[2])
print( a[0:3])
#  similar to python lists  
a[2:4]=10
print(a)

3
[1 2 3]
[ 1  2 10 10  5]


Multi dimensional array

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
n_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#list of lists  
# 2d array
print(n_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(n_2d[1,2])
#row  1, col 2

n_2d[1,2] = 20
print(n_2d[1,2])
#change value at row 1, col 2


7
20


In [19]:
#rewrite entire row in 2d array
n_2d[2] = [9,10,11,12]
print(n_2d)

[[ 1  2  3  4]
 [ 5  6 20  8]
 [ 9 10 11 12]]


In [23]:
# fetch all rows first elements
print(n_2d[:,0])

[1 5 9]


Randomly distribution

In [ ]:
np.random.rand(3,4)
#different random values each time

array([[0.67021495, 0.18915976, 0.44016473, 0.49678864],
       [0.8900298 , 0.90264993, 0.7397645 , 0.53527372],
       [0.91291034, 0.06429699, 0.56729173, 0.95200859]])

In [ ]:
np.random.seed(2)
#same random values each time
np.random.rand(5,2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [27]:
#random normal distrubt ion 
100*np.random.randn(4,2)

array([[ 53.90583206, -59.61596998],
       [ -1.91304965, 117.50012195],
       [-74.78709493,   0.9025251 ],
       [-87.81078932, -15.64341704]])

In [ ]:
np.random.randint(0,10,(3,4))
#random integers between 0 and 10
# 10 is exclusive

array([[0, 4, 2, 4],
       [1, 7, 8, 2],
       [9, 8, 7, 1]], dtype=int32)

Element wise operations

In [33]:
n=np.arange(5)
n

array([0, 1, 2, 3, 4])

In [36]:
print(n+1)
# in python we cannot add a scalar to a list
# but in numpy we can add a scalar to an array
print(n*2)
print(10+ (n*2)/3)


[1 2 3 4 5]
[0 2 4 6 8]
[10.         10.66666667 11.33333333 12.         12.66666667]


In [37]:
a=10+ (n*2)/4
b=n

a+b

array([10. , 11.5, 13. , 14.5, 16. ])

Comparision operation

In [43]:
b=a/6
print(b)
b >= 2
#which elements in a are greater than 2

[1.66666667 1.75       1.83333333 1.91666667 2.        ]


array([False, False, False, False,  True])

In [ ]:
a> b
#comparision operation of each element of a with each element of b
# returns boolean array

array([ True,  True,  True,  True,  True])

In [48]:
a[a> b]
#which elements in a are greater than corresponding elements in b
# all elements of a where condition is true

array([10. , 10.5, 11. , 11.5, 12. ])

In [51]:
# summarizing arrays#
print(a)
np.sum(a)

[10.  10.5 11.  11.5 12. ]


np.float64(55.0)

In [52]:
a.min()

np.float64(10.0)

In [55]:
a.sort()
print(a)

[10.  10.5 11.  11.5 12. ]


In [65]:
n2d=np.random.randint(0,10,(3,4))
print(n2d)
print(n2d.sum(axis=0)) #sum of each column
print(n2d.sum(axis=1)) #sum of each row
#total sum 
print( np.sum(n2d))

[[7 4 3 6]
 [1 4 0 8]
 [5 4 2 9]]
[13 12  5 23]
[20 13 20]
53


In [ ]:
np.random.seed(2)
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))
print(a)
print(50*"*")
print(b)
a*b
#`element wise multiplication, each element of a is multiplied by corresponding element of b`


[[8 8]
 [6 2]]
**************************************************
[[8 7]
 [2 1]]


array([[64, 56],
       [12,  2]], dtype=int32)

In [ ]:
# topics covered
#array multiplication,array addition, array subtraction, matrix multiplication, 


array([[80, 64],
       [52, 44]], dtype=int32)